# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
     python: "mambaforge-22.9"
  commands:
    - mkdir build
    - mamba env create --file environment.yml
    - ln -s $(mamba run -n cycles which pip | rev | cut -d/ -f3- | rev)/lib/libudev.so.1 $(mamba run -n cycles which pip | rev | cut -d/ -f3- | rev)/lib/libudev.so.0
    - cd build && mamba run -n cycles cmake .. && mamba run -n cycles make -j4 all
    - mv build/docs/sphinx/html $READTHEDOCS_OUTPUT/html
    
conda:
  environment: environment.yml
